.ll 200
.TH CAT 2 "GNU coreutils 8.25" "Март 2019"
.SH ОПИСАНИЕ
.PP 
Утилита cat предназначена для объединения и вывода содержимого файлов, поданных ей в качестве аргументов, на стандартный поток вывода.
.br
При отсутствии файлов в качестве аргументов происходит чтение стандартного потока ввода.
.SH СИНОПСИС
.PP
cat [ОПЦИИ] ... [ФАЙЛЫ] ...
.SH ОПЦИИ
.PP 
Ниже представлены ключи для данной команды и их описание:
.TP
-n, --number 
.br 
нумеровать строки при выводе
.TP
-b, --number-nonblank 
.br 
нумеровать строки при выводе, учитывая только непустые строки (перезаписывает -n)
.TP
-v, --show-nonprinting 
.br 
при выводе содержимого файла показывать также непечатные символы, кроме табуляций и символов конца строки
.TP
-e \t
при выводе содержимого файла выводятся также непечатные символы, кроме табуляций, в конце каждой строки ставится $
.TP
-Е, --show-ends
.br 
при выводе файла в конце каждой строки ставится $, другие непечатные символы не выводятся
.TP
-t \t
при выводе содержимого файла выводятся также непечатные символы, кроме символов конца строки, табуляции обозначаются как ^I
.TP
-T, --show-tabs 
.br 
при выводе содержимого файла отображать табуляции как ^I, другие непечатные символы не выводятся
.TP
-А, --show-all
.br 
при выводе содержимого файла показывать непечатные символы, включая символы конца строки (обозначаются как $) и табуляции (обозначаются как ^I)
.TP
-s, --squeeze-blank
.br 
при выводе содержимого файла несколько идущих подряд пустых строк преобразуются в одну
.TP
--help 
.br 
вывести справку по работе с командой и выйти
.TP
--version 
.br 
вывести информацию о версии утилиты и выйти
.SH ПРИМЕРЫ
.TP
cat -nT file1
.br
Вывести содержимое file1 на стандартный поток вывода, пронумеровав все строки и обозначив табуляции как ^I
.TP
cat --version
.br
Получить информацию о версии утилиты
.SH АВТОРЫ
.PP
Torbjorn Granlund и Richard M. Stallman.
.SH СООБЩИТЬ ОБ ОШИБКЕ
Онлайн-справка по системным утилитам GNU: <http://www.gnu.org/software/coreutils/>
.br
Доложить об ошибке cat <http://translationproject.org/team/>
.SH АВТОРСКОЕ ПРАВО
.PP
Copyright © 2016 Free Software Foundation, Inc.  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
Это бесплатное программное обеспечение: вы можете распростанять и изменять его. Нет никаких гарантий до степени, разрешенной законом.
.SH СМОТРИТЕ ТАКЖЕ
.PP
Полная документация: <http://www.gnu.org/software/coreutils/cat>
