#!/bin/bash

if [ -z "$1" ]; then
	echo "Please, write username"
	exit
fi	    

if getent passwd $1 > /dev/null 2>&1; then
	user=`getent passwd "$1" | awk -F':' '{ print $3 }'`
	for curr_file in *; do
	    if [ ! -d "$curr_file" ]; then
			# ls -n: like -l, but list numeric user and group IDs
			curr_file_uid=`ls -n "$curr_file" | awk '{ print $3 }'` 
			curr_file_guid=`ls -n "$curr_file" | awk '{ print $4 }'`
			# check if user is owner
			if [ "$user" = "$curr_file_uid" ]; then
				ls -l "$curr_file" | grep '^.r' > /dev/null && echo "$curr_file"
				continue
			fi
			# check if user in group
			for group in `groups "$1"`; do
				gid=`getent group "$group" | awk -F':' '{ print $3 }'`
				if [ "$gid" = "$curr_file_guid" ]; then
					ls -l "$curr_file" | grep '^....r' > /dev/null && echo "$curr_file"
					continue 2 # done - go to outer loop for next file
				fi	
			done	
			# check if others can read it
			ls -l "$curr_file" | grep '^.......r' > /dev/null && echo "$curr_file"	
		fi
	done
else 
    echo 'No such user'
	exit
fi