#!/bin/bash

results=()

if [ -z "$1" ]; then
	  echo "You should choose directory"
	  exit
fi	    

if [ ! -d "$1" ]; then
	  echo "No such directory found!"
	  exit
fi	  

for curr_file in $1/* 
do
    if [ -p "$curr_file" ]; then
	  if [ ! -z $(lsof $curr_file | awk '$4~/[[:digit:]]*w/' | tr " " "|") ] ; then
        results+=("$(basename "$curr_file") PID - $(lsof $curr_file | grep "$curr_file" | grep " [0-9]w  " | awk '{print $2}')")
	  fi	
    fi
done 

if [ -z "$results" ]; then
	echo "No such pipes found..."
else
    printf '%s\n' "${results[@]}" | sort
fi



